services:
  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_LOG_RETENTION_HOURS: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 5s
      timeout: 10s
      retries: 20

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: search-events
      KAFKA_GROUP_ID: search-top-consumer
      HTTP_ADDR: :8080
      TOP_N: "10"
      CACHE_REFRESH: "1s"
      ANOMALY_WINDOW: "1m"
      ANOMALY_THRESHOLD: "20"
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure